## Adding, removing, and sorting elements

In [1]:
import numpy as np

---

# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [2]:
x = np.zeros((5, 5))

In [3]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [5]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [7]:
def is_prime(n):
    if n == 1:
        return False
    if n == 2:
        return True
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

In [8]:
a = np.arange(1, 26).reshape(5, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
prima = []
for line in a:
    for item in line:
        if is_prime(item):
            prima.append(item)
            
b = np.array(prima)
b

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

In [10]:
c = np.array([item for item in a.flatten() if is_prime(item)])
c

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])